### ISSUE TITLE
Scripts files are webpacked/minified in source code

### ISSUE THREAD

**Issue by rhclayto** [RandomFractals/vscode-data-preview#110]
All the files in the scripts directory in this repository are webpacked/minified. Is this intentional? It seems like webpacking would be part of the build & packaging process, & the source code would stay unminified, or am I wrong?

I would be interested in looking at those files, for my own edification. I'm just getting into VSCode extension building & this extension is SUPER COOL! And reading the code is very helpful.

**Comment by RandomFractals** [comment]
that is intentional. the scripts come from '/scripts' dir. the rest is loadded from [data.view.html](https://github.com/RandomFractals/vscode-data-preview/blob/master/templates/data.view.html) template via sripts tag & some very vanilla JS inlines. I do intend to change that later.

However, it should be be easy to follow, if you start from 'package.json', then 'extensions.ts', etc.

I'll close this ticket if you don't mind since I did not see a real issue or code question there.

Thanks for your input! :)
