### ISSUE TITLE
Unexpected token in JSON at position 14488

### ISSUE THREAD

**Issue by peter197321** [RandomFractals/vscode-data-preview#160]
I try to use my JSON data and during import, I have this error:

Unable to parse data file: '~\data.json'. Error: Unexpected token in JSON at position 14488

**Comment by RandomFractals** [comment]
is it a valid json data file? & can you share it?

**Comment by peter197321** [comment]
I can share that file - where can I share it?

**Comment by peter197321** [comment]
[data.json.zip](https://github.com/RandomFractals/vscode-data-preview/files/3841147/data.json.zip)

**Comment by peter197321** [comment]
just rename  (remove .zip extension)

**Comment by RandomFractals** [comment]
well, it is not a valid json data file. You have a trailing come at line 414. see pic below.

Once I got rid of it, I could load it in Data Preview.

However, please keep in mind json data files with nested structures are converted to flat properties display. see docs for more info on that.

I am gonna close this ticket as invalid. Please make sure your json data has no problems in vscode before you try to load it in my extension. I believe it reported that error correctly since it could not parse your json data :)
![invalid-json-data](https://user-images.githubusercontent.com/656833/68766019-b58f3d80-05e3-11ea-8573-b8fbba04c8e3.png)

**Comment by peter197321** [comment]
Thanks!
