### ISSUE TITLE
Export interactive chart?

### ISSUE THREAD

**Issue by mhkeller** [RandomFractals/vscode-data-preview#194]
Is it possible, or would be possible to add a feature where you export the charts you create? For example, you could export as an HTML file with all the JS in it so you can send that file around to people.

**Comment by RandomFractals** [comment]
this has been on my todo list for some time. see #10

**Comment by mhkeller** [comment]
Neat. Do you have a sense of how this would work and what the relevant files are to look at in the code base? I'd be up for trying to figure out an approach.

**Comment by RandomFractals** [comment]
@mhkeller it's rather complicated. There are generic ways to create png and svg from canvas charts as I pointed out in the related links in #10 I left it open since I've been waiting perhaps d3fc and perspective js developers would provide that interface or at least access to their chart canvas for us to do it.

If you don't mind I'll close  this as a duplicate. Please use my original ticket for logging more info related to this.

Thanks
