### ISSUE TITLE
Column labels strings not visible completely after extending also

### ISSUE THREAD

**Issue by Manikandan-Raju** [RandomFractals/vscode-data-preview#287]
![image](https://user-images.githubusercontent.com/67756241/127780902-7d0fb342-79e1-4b3a-ae00-4f4ca62c0eeb.png)

It would be better if i could see complete strings after extending

**Comment by RandomFractals** [comment]
@Manikandan-Raju looks like your data has very long field names.

I would suggest you trim them. I am not even sure where this sample screengrab data comes from.

Maybe you should drop your table name prefixes in that dataset for a cleaner preview.

I am going to close this request since I don't plan to work on this enhancement.

Thanks for your feedback.
